copy /b/v/y default-0.png default-1.png
copy /b/v/y default-0.png default-2.png
copy /b/v/y default-0.png default-3.png
copy /b/v/y default-0.png default-4.png
copy /b/v/y default-0.png default-5.png
copy /b/v/y default-0.png default-6.png
copy /b/v/y default-0.png default-7.png
copy /b/v/y default-0.png default-8.png
copy /b/v/y default-0.png default-9.png